server:
  port: 8080
#tomcat:
#  jdbc:
#    pool:
#      driverClassName: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/bootdb?useUnicode=true&characterEncoding=utf8&allowMutiQueries=true&useSSL=false
#      username: root
#      password: 123456
spring:
  redis:
    host: localhost
    port: 6379
    database: 10
    password:
  datasource:
    bootdb:
      driverClassname: com.mysql.jdbc.Driver
#2.0的jdbcurl改名参数名改为jdbc-url 不然会报找不到url
      jdbc-url: jdbc:mysql://127.0.0.1:3306/bootdb?useUnicode=true&characterEncoding=utf8&allowMutiQueries=true&useSSL=false
      username: root
      password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.winterchen.model
